DRAFT: Refactor handlers long files into modules
bermed28/bot-discord pull request #53
Opened 2021-06-24 04:07 UTC by agSant01

# Overview

*Coming soon.

Closes #51

2021-06-26 01:49 UTC, bermed28 requested changes

2021-06-26 01:49 UTC, bermed28 commented on handlers/telephone_guide/faculty.py
> +    "Manuel Rodriguez Martinez": "Associate Director\nFull Time Professor\nmanuel.rodriguez7@upr.edu",
Manuel ya no es Director Asociado

2021-06-26 01:49 UTC, bermed28 commented on handlers/telephone_guide/faculty.py
> +    "Emmanuel Arzuaga Cruz": "Full Time Professor\nearzuaga@ece.uprm.edu",
Arzuaga es Director Asociado

2021-06-26 01:49 UTC, bermed28 commented on handlers/telephone_guide/faculty.py
> +    "Juan O. Lopez Gerena": "Instructor\njuano.lopez@upr.edu"
Juan Lopez ya no esta en RUM, es director del dept de CS en UPRA, needs to be removed

2021-06-26 01:49 UTC, bermed28 commented on handlers/telephone_guide/faculty.py
> +    "Jaime Seguel": "Retired\njaime.seguel@upr.edu",
Retired, removed

2021-06-26 01:49 UTC, bermed28 commented on handlers/telephone_guide/faculty.py
> +    "Jaime Arbona Fazzi": "Full Time Professor\njaime.arbona@upr.edu",
Retired

2021-06-29 20:21 UTC, agSant01 commented on handlers/telephone_guide/faculty.py
> +    "Jaime Seguel": "Retired\njaime.seguel@upr.edu",
Cual linea de la 19-22?

2021-06-29 20:22 UTC, agSant01 commented on handlers/telephone_guide/faculty.py
> +    "Jaime Arbona Fazzi": "Full Time Professor\njaime.arbona@upr.edu",
Arbona?

2021-07-06 17:53 UTC, bermed28 approved these changes

2021-07-06 19:09 UTC, merged