List of student projects
bermed28/bot-discord pull request #59
Opened 2021-07-25 19:02 UTC by karelyslopez18

2021-07-28 16:04 UTC, bermed28 commented on event_handlers/actions.py
> +                    await message.author.send("Esta es la información del "+ key + " : " + proyectos[key])
use as reference the following to see if we can optimize it a little bit:
```
orgsDict = {
    “IEEE” : [“IEEE”, “Descprition”,”contact info”],
    “CAHSI”: [“CAHSI Msg”]
} 
key = split[1].upper()
if key in orgsDict:
  info = orgsDict[key]
  for i in range(len(info)):
    await message.author.send(info[i])
```

2021-07-28 16:09 UTC, bermed28 requested changes
Try to optimize the algorithm to extract information from JSON file, look at the comment I left you. It's the same algorithm that I showed Carolina. Take advantage of that hashtable lookup & extraction is O(1)

2021-07-28 16:29 UTC, agSant01 requested changes

2021-07-28 16:29 UTC, agSant01 commented on event_handlers/actions.py
> +    project_ds_path = os.path.join(code_dir, '../res/proyectis/proyectos.json')
Utilizar el modulo constants/paths para este file path. Con utilizar eso la linea 167 no es necesaria.

2021-07-28 16:29 UTC, agSant01 commented on event_handlers/actions.py
> +                else:
Aca en este bloque tengo unas cuantas sugerencias, 
Ya me reuni con Carolina a discutir estas cosas. Me puedes preguntar a ella o a mi.

Van por la linea de como reducir el nesting de if's cambiando la logica utilizando negaciones y flow-guards ("returns" dentro de if-blocks para cortar e flujo de control sin tener que usar else's que no tienen condicion y ningun codigo para ejecutar despues).

Otra cosa es que como ese JSON no se va a cambiar durante el runtime de la aplicacion se puede hacer el `load()` solo una vez y mantener esa data en memoria. Se ahora el abrir y cerrar archivos por cada vez que se ejecuta el comando.

2021-07-28 16:29 UTC, agSant01 commented on event_handlers/actions.py
> +        if "!ls_projects" in user_message.lower():
Observacion:

Verificar si el mensaje contiene el <cmd> antes de abrir el archivo. Habrir el archivo da una penalidad de recursos y clock-cycles y no se deberia hacer si no es necesario.

La primera instruccion de la funcion puede ser esta:

```python
if "!ls_projects" not in user_message.lower():
     return
```

Y asi se corta el flujo rapido.

2021-07-28 16:29 UTC, agSant01 commented on event_handlers/actions.py
> +async def get_prj_info(message: discord.Message):
Nombre de la funcion puede tener la palabra completa `project`.

2021-07-28 16:34 UTC, agSant01 commented
Pregunta, hay algun feedback para el usuario de si escribe el commando pero con unas siglas que no estan en el JSON, aka. se equivoca, etc?

2021-07-31 04:52 UTC, agSant01 approved these changes

2021-07-31 04:52 UTC, merged